#!/usr/bin/env bash
set -e

cmd=$1
shift

remote_head() {
    hg identify --id "$(hg paths default)#$1" 2> /dev/null
}

current_rev() {
    hg identify -n | sed 's/[^0-9]*//g'
}

case $cmd in
    "blame")
        hg annotate -cdu "$@"
        ;;
    "br")
        if [ -z "$@" ]; then
            hg branches
        else
            hg branch "$@"
        fi
        ;;
    "fetch")
        hg pull
        ;;
    "log")
        hg log -G --template "\033[1;33mcommit: {rev}:{node|short}{if(bookmarks, ' \033[46m\033[1;37m ', '')}{join(bookmarks, ' \033[0m \033[46m\033[1;37m ')}{if(bookmarks, ' \033[0m', '')}{if(tags, ' \033[45m\033[1;37m ', '')}{join(tags, ' \033[0m \033[45m\033[1;37m ')}{if(tags, ' \033[0m', '')}\nAuthor: {author}\nDate:   {date|isodate}\n\n\t{desc|strip|fill68|tabindent}\n\n" -r ::$(current_rev)
        ;;
    "remote")
        hg update $(remote_head $1)
        ;;
    "stash")
        if [ "$1" = "pop" ]; then
            hg unshelve
        else
            hg stash
        fi
        ;;
    "undo")
        hg revert --no-backup "$@"
        ;;
    *)
        hg $cmd "$@"
esac
