#!/usr/bin/env bash
set -e

cmd=$1
shift

remote_head() {
    hg identify --id "$(hg paths default)#$1" 2> /dev/null
}

current_rev() {
    hg identify -n | sed 's/[^0-9]*//g'
}

case $cmd in
    "blame")
        hg annotate -cdu "$@"
        ;;
    "br")
        if [[ -z "$@" ]]; then
            hg branches
        else
            hg branch "$@"
        fi
        ;;
    "changes")
        if [[ -z "$@" ]]; then
            hg plog $(hg slog | peco | awk "{print \$1}")
        else
            hg plog $(hg slog "$1" | peco | awk "{print \$1}") "$1"
        fi
        ;;
    "fetch")
        hg pull $1
        ;;
    "log")
        hg log -G --template "\033[1;33mcommit: {rev}:{node|short}{if(bookmarks, ' \033[46m\033[1;37m ', '')}{join(bookmarks, ' \033[0m \033[46m\033[1;37m ')}{if(bookmarks, ' \033[0m', '')}{if(tags, ' \033[45m\033[1;37m ', '')}{join(tags, ' \033[0m \033[45m\033[1;37m ')}{if(tags, ' \033[0m', '')}\nAuthor: {author}\nDate:   {date|isodate}\n\n\t{desc|strip|fill68|tabindent}\n\n" -r ::$(current_rev)
        ;;
    "stash")
        if [ "$1" = "pop" ]; then
            hg unshelve
        else
            hg shelve
        fi
        ;;
    "undo")
        hg revert --no-backup "$@"
        ;;
    "update")
        if [ "$1" = "remote" ]; then
            hg update $(remote_head $2)
        else
            hg update "$@"
        fi
        ;;
    *)
        hg $cmd "$@"
esac
