#!/usr/bin/env bash
set -e
exec 2> /dev/null

current_path=`pwd`
cmd=$1
shift

if ! which direnv > /dev/null; then
    echo "direnv: command not found"
    exit 1
fi

init() {
cat <<- EOF > $current_path/.envrc
path_add PYTHONUSERBASE .pip
PATH_add .pip/bin
EOF
direnv allow .
}

case $cmd in
    "init")
        if [ -e "$current_path/.envrc" ]; then
            echo ".envrc already exists."
            exit 1
        fi
        init
        ;;
    "install")
        if [ -z "$PYTHONUSERBASE" ]; then
            echo "Use need to run 'pip init' first."
            exit 1
        fi
        pip install --user "$@"
        ;;
    *)
        pip $cmd "$@"
        ;;
esac
